apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: plex
resources:
  - deployment.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - service.yaml
#  - ingress.yaml