apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config
  labels:
    name: config
    type: local
spec:
  storageClassName: config
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/plexmediaserver"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-transcode
  labels:
    name: transcode
    type: local
spec:
  storageClassName: transcode
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-data
  labels:
    name: data
    type: local
spec:
  storageClassName: data
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
