---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: plex
  namespace: plex-prd
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:*
spec:
  releaseName: plex
  chart:
#    git: ssh://APKARQMOF42EGBWJQZPD@git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/env-dolltime-mythbox-k8s
#    git: ssh://git@github.com/dab9171355/env-dolltime-mythbox-k8s-public
    git: https://github.com/dab9171355/env-dolltime-mythbox-k8s-public
    ref: master
    path: charts/plex
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.19.3.2831-181d9145d
      env:
        plexUid: "1000"
        plexGid: "44"
        tz: "Australia/Melbourne"
    service:
      type: NodePort
    volumes:
      config: "/var/lib/plexmediaserver"
      transcode: "/tmp"
      data: "/home/dab/videos"
