apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-postgresql-data
  labels:
    type: local
    name: jira-postgresql-data
spec:
  storageClassName: jira-postgresql-data
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /home/k8s/jira-postgresql-data
