apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
spec:
  selector:
    matchLabels:
      env: production
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-transcode
spec:
  selector:
    matchLabels:
      env: production
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data
spec:
  selector:
    matchLabels:
      env: production
