---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: confluence-postgresql
  namespace: atlassian-npd
  annotations:
    fluxcd.io/automated: 'true'
    fluxcd.io/tag.chart-image: glob:8.9.*
spec:
  releaseName: confluence-postgresql
  chart:
    git: https://github.com/bitnami/charts
    ref: master
    path: bitnami/postgresql
  values:
    postgresqlDatabase: confluencedb
    persistence:
      storageClass: confluence-postgresql-data
