apiVersion: v1
kind: PersistentVolume
metadata:
  name: confluence-data
  labels:
    type: local
    name: confluence-data
spec:
  storageClassName: confluence-data
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/k8s/confluence-data
