---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: confluence-server
  namespace: atlassian-npd
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:2.1.*
spec:
  releaseName: confluence
  chart:
    git: https://github.com/dab9171355/helm-charts
    ref: master
    path: charts/confluence-server
  values:
    image:
      tag: 7.4.0
    service:
      type: NodePort
    persistence:
      enabled: true
      storageClass: confluence-data
    psql:
      host: confluence-postgresql
      port: 5432
      database: confluencedb
      username: confluenceuser
      password:
        secret: confluence-secrets
        key: postgresql-password
